using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;

namespace DZ6.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

public class PostModel
{
    [Key]
    public int Id { get; set; }
    
    [Required]
    [MaxLength(256)]
    [Display(Name = "Title", Description = "Title of the post")]
    public string Title { get; set; }
    
    [Required]
    [MaxLength(256)]
    [Display(Name = "Slug", Description = "Title of the post")]
    public string Slug { get; set; }
    
    [Required]
    [MaxLength(2048)]
    [Display(Name = "Content", Description = "Content of the post")]
    public string Content { get; set; }
    
    [ForeignKey("Author")]
    public string AuthorId { get; set; }
    public MyIdentityUser Author { get; set; }
    
    [Display(Name = "Created at", Description = "Timestamp when the record was created (generated by the database)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime CreatedAt { get; set; }
    
    [Display(Name = "Updated at", Description = "Timestamp of last update (computed by the database)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime? UpdatedAt { get; set; }
    
    [Display(Name ="Tags", Description = "Tags of the post")]
    public ICollection<TagModel> Tags { get; set; } = new List<TagModel>();

    [NotMapped]
    public List<int> SelectedTagIds { get; set; } = new List<int>();

    public PostModel()
    {
        CreatedAt = DateTime.UtcNow;
    }
    
    
}